### ISSUE TITLE
Quote Command discord error

### ISSUE THREAD

**Issue by Blvckleg** [Blvckleg/BingusBoingus#57]
**Describe the bug**
Beim Speichern einer neuen Quote kann es sein dass es zu lange dauert und der Command token nicht mehr gueltig ist.
-> response dauert zu lange -> discord error obwohl es funktioniert.

**To Reproduce**
1. use /quote and save a quote
2. See error in chat

**Expected behavior**
Kein Error beim erfolgreichen speichern -> `await interaction.deferReply()` um auf response zu warten

**Desktop (please complete the following information):**
 - OS: Any OS
 - Bingus 1.1.1

**Additional context**

**Comment by Blvckleg** [comment]
Funktioniert meistens. Manchmal dauert es zu lange. Reply defer sollte das problem loesen

**Comment by lulu12329** [comment]
Es wird aktuell nie auf den Command geantwortet: 

`arg.channel.send({ embeds: [quoteEmbed] });` => `arg.reply({ embeds: [quoteEmbed] });`
